## 4.2 损失函数的定义

### 1. 经典损失函数

In [ ]:
import tensorflow as tf

#分类问题损失函数，交叉熵
cross_entropy = tf.nn.softmax_cross_entropy_with_logits(label=y_, logits=y)

#回归问题损失函数，均方误差（MSE，mean squared error）
mse = tf.reduce_mean(tf.square(y_ - y))

### 2. 自定义损失函数

In [7]:
import tensorflow as tf

v1 = tf.constant([1.0, 2.0, 3.0, 4.0])
v2 = tf.constant([4.0, 3.0, 2.0, 1.0])

#自动将生成的会话注册成会话
#tf.greater()和tf.where()的使用
sess = tf.InteractiveSession()
print(tf.greater(v1, v2).eval())

print(tf.where(tf.greater(v1, v2), v1, v2).eval())

[False False  True  True]
[ 4.  3.  3.  4.]


C:\Users\ustc-nanmu\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [12]:
import tensorflow as tf
from numpy.random import RandomState

batch_size = 8

#两个输入节点
x = tf.placeholder(tf.float32, shape=(None, 2), name='x-input')
y_ = tf.placeholder(tf.float32, shape=(None, 1), name='y-input')

w1 = tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#自定义损失函数
loss_less = 10
loss_more = 1
loss = tf.reduce_sum(tf.where(tf.greater(y, y_),
                             (y - y_) * loss_more,
                             (y - y_) * loss_less))
train_step = tf.train.AdadeltaOptimizer(0.001).minimize(loss)

rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size, 2)
Y = [[x1 + x2 + rdm.rand() / 10.0 - 0.05] for (x1, x2) in X]

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i * batch_size) % dataset_size
        end = min(start + batch_size, dataset_size)
        sess.run(train_step,  feed_dict={x: X[start:end], y_: Y[start:end]})
        print(sess.run(w1))
                                         

[[-0.8113187 ]
 [ 1.48459828]]
[[-0.81131923]
 [ 1.4845978 ]]
[[-0.81131995]
 [ 1.48459733]]
[[-0.81132048]
 [ 1.48459697]]
[[-0.8113212 ]
 [ 1.48459649]]
[[-0.81132185]
 [ 1.48459589]]
[[-0.81132251]
 [ 1.48459542]]
[[-0.81132317]
 [ 1.48459494]]
[[-0.81132388]
 [ 1.48459446]]
[[-0.81132436]
 [ 1.48459399]]
[[-0.81132489]
 [ 1.48459339]]
[[-0.81132543]
 [ 1.48459303]]
[[-0.81132627]
 [ 1.48459232]]
[[-0.81132674]
 [ 1.48459184]]
[[-0.8113274 ]
 [ 1.48459113]]
[[-0.81132793]
 [ 1.48459041]]
[[-0.81132823]
 [ 1.48459005]]
[[-0.81132871]
 [ 1.48458958]]
[[-0.81132942]
 [ 1.48458898]]
[[-0.8113299 ]
 [ 1.48458874]]
[[-0.81133068]
 [ 1.48458838]]
[[-0.81133133]
 [ 1.48458779]]
[[-0.81133199]
 [ 1.48458731]]
[[-0.81133264]
 [ 1.48458683]]
[[-0.81133336]
 [ 1.48458636]]
[[-0.81133384]
 [ 1.48458588]]
[[-0.81133437]
 [ 1.48458529]]
[[-0.81133491]
 [ 1.48458493]]
[[-0.81133574]
 [ 1.48458421]]
[[-0.81133622]
 [ 1.48458374]]
[[-0.81133687]
 [ 1.48458302]]
[[-0.81133741]
 [ 1.4845823 ]]
[[-0.811

[[-0.81156725]
 [ 1.48437202]]
[[-0.81156796]
 [ 1.48437119]]
[[-0.81156862]
 [ 1.48437035]]
[[-0.81156892]
 [ 1.48436987]]
[[-0.81156945]
 [ 1.48436928]]
[[-0.81157029]
 [ 1.48436868]]
[[-0.81157082]
 [ 1.48436832]]
[[-0.81157166]
 [ 1.48436785]]
[[-0.81157237]
 [ 1.48436713]]
[[-0.81157309]
 [ 1.48436654]]
[[-0.8115738 ]
 [ 1.48436594]]
[[-0.81157464]
 [ 1.48436546]]
[[-0.81157517]
 [ 1.48436487]]
[[-0.81157577]
 [ 1.48436415]]
[[-0.81157637]
 [ 1.48436368]]
[[-0.81157732]
 [ 1.48436284]]
[[-0.81157786]
 [ 1.48436224]]
[[-0.81157863]
 [ 1.48436141]]
[[-0.81157929]
 [ 1.48436058]]
[[-0.81157959]
 [ 1.4843601 ]]
[[-0.81158012]
 [ 1.4843595 ]]
[[-0.81158096]
 [ 1.48435891]]
[[-0.81158149]
 [ 1.48435855]]
[[-0.81158233]
 [ 1.48435807]]
[[-0.81158304]
 [ 1.48435736]]
[[-0.81158376]
 [ 1.48435676]]
[[-0.81158447]
 [ 1.48435616]]
[[-0.81158531]
 [ 1.48435569]]
[[-0.81158584]
 [ 1.48435509]]
[[-0.81158644]
 [ 1.48435438]]
[[-0.81158704]
 [ 1.4843539 ]]
[[-0.81158799]
 [ 1.48435307]]
[[-0.811

[[-0.81177348]
 [ 1.48417997]]
[[-0.81177413]
 [ 1.48417914]]
[[-0.81177479]
 [ 1.48417866]]
[[-0.8117758 ]
 [ 1.48417771]]
[[-0.81177634]
 [ 1.48417711]]
[[-0.81177711]
 [ 1.48417616]]
[[-0.81177777]
 [ 1.48417532]]
[[-0.81177813]
 [ 1.48417485]]
[[-0.81177866]
 [ 1.48417413]]
[[-0.81177956]
 [ 1.48417342]]
[[-0.81178015]
 [ 1.48417306]]
[[-0.81178105]
 [ 1.48417258]]
[[-0.81178182]
 [ 1.48417175]]
[[-0.8117826 ]
 [ 1.48417115]]
[[-0.81178337]
 [ 1.48417056]]
[[-0.81178427]
 [ 1.48416996]]
[[-0.81178486]
 [ 1.48416936]]
[[-0.81178552]
 [ 1.48416853]]
[[-0.81178617]
 [ 1.48416805]]
[[-0.81178719]
 [ 1.4841671 ]]
[[-0.81178772]
 [ 1.4841665 ]]
[[-0.8117885 ]
 [ 1.48416555]]
[[-0.81178916]
 [ 1.48416471]]
[[-0.81178951]
 [ 1.48416424]]
[[-0.81179005]
 [ 1.48416352]]
[[-0.81179094]
 [ 1.48416281]]
[[-0.81179154]
 [ 1.48416245]]
[[-0.81179243]
 [ 1.48416197]]
[[-0.81179321]
 [ 1.48416114]]
[[-0.81179398]
 [ 1.48416042]]
[[-0.81179476]
 [ 1.48415983]]
[[-0.81179565]
 [ 1.48415923]]
[[-0.811

[[-0.81210452]
 [ 1.48386991]]
[[-0.81210518]
 [ 1.48386908]]
[[-0.81210589]
 [ 1.4838686 ]]
[[-0.81210697]
 [ 1.48386765]]
[[-0.81210756]
 [ 1.48386705]]
[[-0.8121084 ]
 [ 1.48386598]]
[[-0.81210911]
 [ 1.48386502]]
[[-0.81210947]
 [ 1.48386443]]
[[-0.81211007]
 [ 1.48386371]]
[[-0.81211102]
 [ 1.483863  ]]
[[-0.81211168]
 [ 1.48386264]]
[[-0.81211269]
 [ 1.48386204]]
[[-0.81211352]
 [ 1.48386109]]
[[-0.81211436]
 [ 1.48386037]]
[[-0.81211519]
 [ 1.48385966]]
[[-0.81211615]
 [ 1.48385906]]
[[-0.81211674]
 [ 1.48385835]]
[[-0.8121174 ]
 [ 1.48385751]]
[[-0.81211811]
 [ 1.48385704]]
[[-0.81211919]
 [ 1.48385608]]
[[-0.81211978]
 [ 1.48385549]]
[[-0.81212062]
 [ 1.48385441]]
[[-0.81212133]
 [ 1.48385346]]
[[-0.81212169]
 [ 1.48385286]]
[[-0.81212229]
 [ 1.48385215]]
[[-0.81212324]
 [ 1.48385143]]
[[-0.81212389]
 [ 1.48385108]]
[[-0.81212491]
 [ 1.48385048]]
[[-0.81212574]
 [ 1.48384953]]
[[-0.81212658]
 [ 1.48384881]]
[[-0.81212741]
 [ 1.48384809]]
[[-0.81212837]
 [ 1.4838475 ]]
[[-0.812

[[-0.81241518]
 [ 1.48357642]]
[[-0.81241608]
 [ 1.4835757 ]]
[[-0.81241697]
 [ 1.48357499]]
[[-0.81241798]
 [ 1.48357439]]
[[-0.81241864]
 [ 1.48357368]]
[[-0.81241935]
 [ 1.48357284]]
[[-0.81242007]
 [ 1.48357224]]
[[-0.8124212 ]
 [ 1.48357117]]
[[-0.8124218 ]
 [ 1.48357046]]
[[-0.81242269]
 [ 1.48356938]]
[[-0.81242347]
 [ 1.48356843]]
[[-0.81242383]
 [ 1.48356783]]
[[-0.81242442]
 [ 1.48356712]]
[[-0.81242543]
 [ 1.48356628]]
[[-0.81242609]
 [ 1.48356593]]
[[-0.8124271 ]
 [ 1.48356533]]
[[-0.812428  ]
 [ 1.48356438]]
[[-0.81242889]
 [ 1.48356366]]
[[-0.81242979]
 [ 1.48356295]]
[[-0.8124308 ]
 [ 1.48356235]]
[[-0.81243145]
 [ 1.48356164]]
[[-0.81243217]
 [ 1.4835608 ]]
[[-0.81243289]
 [ 1.4835602 ]]
[[-0.81243402]
 [ 1.48355913]]
[[-0.81243461]
 [ 1.48355842]]
[[-0.81243551]
 [ 1.48355734]]
[[-0.81243628]
 [ 1.48355639]]
[[-0.81243664]
 [ 1.48355579]]
[[-0.81243724]
 [ 1.48355508]]
[[-0.81243825]
 [ 1.48355424]]
[[-0.81243891]
 [ 1.48355389]]
[[-0.81243992]
 [ 1.48355329]]
[[-0.812

[[-0.81275606]
 [ 1.48325169]]
[[-0.81275678]
 [ 1.48325074]]
[[-0.81275749]
 [ 1.48325014]]
[[-0.81275868]
 [ 1.48324907]]
[[-0.81275934]
 [ 1.48324835]]
[[-0.81276029]
 [ 1.48324728]]
[[-0.81276107]
 [ 1.48324621]]
[[-0.81276143]
 [ 1.48324561]]
[[-0.81276208]
 [ 1.48324478]]
[[-0.81276315]
 [ 1.48324394]]
[[-0.81276381]
 [ 1.48324347]]
[[-0.81276488]
 [ 1.48324287]]
[[-0.81276578]
 [ 1.48324192]]
[[-0.81276667]
 [ 1.4832412 ]]
[[-0.81276757]
 [ 1.48324049]]
[[-0.81276858]
 [ 1.48323977]]
[[-0.81276923]
 [ 1.48323905]]
[[-0.81276995]
 [ 1.4832381 ]]
[[-0.81277072]
 [ 1.4832375 ]]
[[-0.81277192]
 [ 1.48323643]]
[[-0.81277257]
 [ 1.48323572]]
[[-0.81277353]
 [ 1.48323464]]
[[-0.8127743 ]
 [ 1.48323357]]
[[-0.81277466]
 [ 1.48323298]]
[[-0.81277531]
 [ 1.48323214]]
[[-0.81277639]
 [ 1.48323131]]
[[-0.81277704]
 [ 1.48323083]]
[[-0.81277812]
 [ 1.48323023]]
[[-0.81277901]
 [ 1.48322928]]
[[-0.8127799 ]
 [ 1.48322856]]
[[-0.8127808 ]
 [ 1.48322785]]
[[-0.81278181]
 [ 1.48322713]]
[[-0.812

[[-0.81313807]
 [ 1.4828881 ]]
[[-0.81313902]
 [ 1.48288691]]
[[-0.81313986]
 [ 1.48288584]]
[[-0.81314027]
 [ 1.48288524]]
[[-0.81314093]
 [ 1.48288441]]
[[-0.813142  ]
 [ 1.48288357]]
[[-0.81314272]
 [ 1.4828831 ]]
[[-0.81314385]
 [ 1.4828825 ]]
[[-0.8131448 ]
 [ 1.48288143]]
[[-0.81314576]
 [ 1.48288059]]
[[-0.81314671]
 [ 1.48287988]]
[[-0.81314778]
 [ 1.48287916]]
[[-0.8131485 ]
 [ 1.48287833]]
[[-0.81314927]
 [ 1.48287737]]
[[-0.81315005]
 [ 1.48287678]]
[[-0.81315124]
 [ 1.4828757 ]]
[[-0.8131519 ]
 [ 1.48287499]]
[[-0.81315285]
 [ 1.4828738 ]]
[[-0.81315368]
 [ 1.48287272]]
[[-0.8131541 ]
 [ 1.48287213]]
[[-0.81315476]
 [ 1.48287129]]
[[-0.81315583]
 [ 1.48287046]]
[[-0.81315655]
 [ 1.48286998]]
[[-0.81315768]
 [ 1.48286939]]
[[-0.81315863]
 [ 1.48286831]]
[[-0.81315958]
 [ 1.48286748]]
[[-0.81316054]
 [ 1.48286676]]
[[-0.81316161]
 [ 1.48286605]]
[[-0.81316233]
 [ 1.48286521]]
[[-0.8131631 ]
 [ 1.48286426]]
[[-0.81316388]
 [ 1.48286366]]
[[-0.81316507]
 [ 1.48286259]]
[[-0.813

[[-0.8134253 ]
 [ 1.48261344]]
[[-0.81342602]
 [ 1.48261261]]
[[-0.81342679]
 [ 1.48261166]]
[[-0.81342757]
 [ 1.48261106]]
[[-0.81342882]
 [ 1.48260987]]
[[-0.81342947]
 [ 1.48260915]]
[[-0.81343043]
 [ 1.48260796]]
[[-0.81343126]
 [ 1.48260689]]
[[-0.81343168]
 [ 1.48260629]]
[[-0.81343234]
 [ 1.48260546]]
[[-0.81343347]
 [ 1.48260462]]
[[-0.81343418]
 [ 1.48260415]]
[[-0.81343532]
 [ 1.48260355]]
[[-0.81343627]
 [ 1.48260248]]
[[-0.81343722]
 [ 1.48260164]]
[[-0.81343818]
 [ 1.48260081]]
[[-0.81343925]
 [ 1.48260009]]
[[-0.81343997]
 [ 1.48259926]]
[[-0.81344074]
 [ 1.4825983 ]]
[[-0.81344151]
 [ 1.48259771]]
[[-0.81344277]
 [ 1.48259652]]
[[-0.81344342]
 [ 1.4825958 ]]
[[-0.81344438]
 [ 1.48259461]]
[[-0.81344521]
 [ 1.48259354]]
[[-0.81344563]
 [ 1.48259294]]
[[-0.81344628]
 [ 1.48259211]]
[[-0.81344742]
 [ 1.48259127]]
[[-0.81344813]
 [ 1.48259079]]
[[-0.81344926]
 [ 1.4825902 ]]
[[-0.81345022]
 [ 1.48258913]]
[[-0.81345117]
 [ 1.48258829]]
[[-0.81345212]
 [ 1.48258746]]
[[-0.813

[[-0.81383878]
 [ 1.48221743]]
[[-0.8138395 ]
 [ 1.48221695]]
[[-0.81384063]
 [ 1.48221636]]
[[-0.81384158]
 [ 1.48221529]]
[[-0.81384254]
 [ 1.48221445]]
[[-0.81384349]
 [ 1.48221362]]
[[-0.81384456]
 [ 1.4822129 ]]
[[-0.81384528]
 [ 1.48221207]]
[[-0.81384605]
 [ 1.48221111]]
[[-0.81384683]
 [ 1.48221052]]
[[-0.81384808]
 [ 1.48220932]]
[[-0.81384873]
 [ 1.48220861]]
[[-0.81384975]
 [ 1.48220742]]
[[-0.81385058]
 [ 1.48220634]]
[[-0.813851  ]
 [ 1.48220575]]
[[-0.81385165]
 [ 1.48220491]]
[[-0.81385279]
 [ 1.48220408]]
[[-0.8138535]
 [ 1.4822036]]
[[-0.81385463]
 [ 1.48220301]]
[[-0.81385559]
 [ 1.48220193]]
[[-0.81385654]
 [ 1.4822011 ]]
[[-0.8138575 ]
 [ 1.48220026]]
[[-0.81385857]
 [ 1.48219955]]
[[-0.81385928]
 [ 1.48219872]]
[[-0.81386006]
 [ 1.48219776]]
[[-0.81386083]
 [ 1.48219717]]
[[-0.81386209]
 [ 1.48219597]]
[[-0.81386274]
 [ 1.48219526]]
[[-0.81386375]
 [ 1.48219407]]
[[-0.81386459]
 [ 1.48219299]]
[[-0.81386501]
 [ 1.4821924 ]]
[[-0.81386566]
 [ 1.48219156]]
[[-0.81386

[[-0.81407392]
 [ 1.48199379]]
[[-0.81407475]
 [ 1.48199272]]
[[-0.81407517]
 [ 1.48199213]]
[[-0.81407583]
 [ 1.48199129]]
[[-0.81407696]
 [ 1.48199046]]
[[-0.81407768]
 [ 1.48198998]]
[[-0.81407881]
 [ 1.48198938]]
[[-0.81407976]
 [ 1.48198831]]
[[-0.81408077]
 [ 1.48198748]]
[[-0.81408173]
 [ 1.48198664]]
[[-0.8140828 ]
 [ 1.48198593]]
[[-0.81408352]
 [ 1.48198509]]
[[-0.81408429]
 [ 1.48198414]]
[[-0.81408507]
 [ 1.48198354]]
[[-0.81408632]
 [ 1.48198235]]
[[-0.81408697]
 [ 1.48198164]]
[[-0.81408799]
 [ 1.48198044]]
[[-0.81408882]
 [ 1.48197937]]
[[-0.81408924]
 [ 1.48197877]]
[[-0.81408989]
 [ 1.48197794]]
[[-0.81409103]
 [ 1.48197711]]
[[-0.81409174]
 [ 1.48197663]]
[[-0.81409287]
 [ 1.48197603]]
[[-0.81409383]
 [ 1.48197496]]
[[-0.81409484]
 [ 1.48197412]]
[[-0.8140958 ]
 [ 1.48197329]]
[[-0.81409687]
 [ 1.48197258]]
[[-0.81409758]
 [ 1.48197174]]
[[-0.81409836]
 [ 1.48197079]]
[[-0.81409913]
 [ 1.48197019]]
[[-0.81410038]
 [ 1.481969  ]]
[[-0.81410104]
 [ 1.48196828]]
[[-0.814

[[-0.81433427]
 [ 1.48174703]]
[[-0.81433529]
 [ 1.4817462 ]]
[[-0.81433624]
 [ 1.48174536]]
[[-0.81433737]
 [ 1.48174465]]
[[-0.81433809]
 [ 1.48174381]]
[[-0.81433886]
 [ 1.48174286]]
[[-0.8143397 ]
 [ 1.48174226]]
[[-0.81434095]
 [ 1.48174107]]
[[-0.81434166]
 [ 1.48174036]]
[[-0.81434268]
 [ 1.48173916]]
[[-0.81434351]
 [ 1.48173809]]
[[-0.81434393]
 [ 1.48173749]]
[[-0.81434464]
 [ 1.48173666]]
[[-0.81434578]
 [ 1.48173571]]
[[-0.81434649]
 [ 1.48173523]]
[[-0.81434762]
 [ 1.48173463]]
[[-0.81434864]
 [ 1.48173356]]
[[-0.81434965]
 [ 1.48173273]]
[[-0.81435061]
 [ 1.48173189]]
[[-0.81435174]
 [ 1.48173118]]
[[-0.81435245]
 [ 1.48173034]]
[[-0.81435323]
 [ 1.48172939]]
[[-0.81435406]
 [ 1.48172879]]
[[-0.81435531]
 [ 1.4817276 ]]
[[-0.81435603]
 [ 1.48172688]]
[[-0.81435704]
 [ 1.48172569]]
[[-0.81435788]
 [ 1.48172462]]
[[-0.81435829]
 [ 1.48172402]]
[[-0.81435901]
 [ 1.48172319]]
[[-0.81436014]
 [ 1.48172224]]
[[-0.81436086]
 [ 1.48172176]]
[[-0.81436199]
 [ 1.48172116]]
[[-0.814

[[-0.81457645]
 [ 1.48152089]]
[[-0.81457758]
 [ 1.48151994]]
[[-0.81457829]
 [ 1.48151946]]
[[-0.81457949]
 [ 1.48151875]]
[[-0.8145805 ]
 [ 1.48151767]]
[[-0.81458151]
 [ 1.48151684]]
[[-0.81458253]
 [ 1.481516  ]]
[[-0.81458366]
 [ 1.48151529]]
[[-0.81458437]
 [ 1.48151445]]
[[-0.81458515]
 [ 1.4815135 ]]
[[-0.81458598]
 [ 1.4815129 ]]
[[-0.8145873 ]
 [ 1.48151171]]
[[-0.81458801]
 [ 1.481511  ]]
[[-0.81458902]
 [ 1.4815098 ]]
[[-0.81458992]
 [ 1.48150873]]
[[-0.81459033]
 [ 1.48150814]]
[[-0.81459105]
 [ 1.4815073 ]]
[[-0.81459218]
 [ 1.48150635]]
[[-0.8145929 ]
 [ 1.48150587]]
[[-0.81459409]
 [ 1.48150516]]
[[-0.8145951 ]
 [ 1.48150408]]
[[-0.81459612]
 [ 1.48150325]]
[[-0.81459713]
 [ 1.48150241]]
[[-0.81459826]
 [ 1.4815017 ]]
[[-0.81459898]
 [ 1.48150086]]
[[-0.81459975]
 [ 1.48149991]]
[[-0.81460059]
 [ 1.48149931]]
[[-0.8146019 ]
 [ 1.48149812]]
[[-0.81460261]
 [ 1.48149741]]
[[-0.81460363]
 [ 1.48149621]]
[[-0.81460452]
 [ 1.48149514]]
[[-0.81460494]
 [ 1.48149455]]
[[-0.814

[[-0.81483793]
 [ 1.48127878]]
[[-0.81483883]
 [ 1.4812777 ]]
[[-0.81483924]
 [ 1.48127711]]
[[-0.81483996]
 [ 1.48127627]]
[[-0.81484109]
 [ 1.48127532]]
[[-0.81484187]
 [ 1.48127484]]
[[-0.81484306]
 [ 1.48127413]]
[[-0.81484407]
 [ 1.48127306]]
[[-0.81484509]
 [ 1.48127222]]
[[-0.8148461 ]
 [ 1.48127139]]
[[-0.81484723]
 [ 1.48127067]]
[[-0.81484795]
 [ 1.48126984]]
[[-0.81484872]
 [ 1.48126888]]
[[-0.81484956]
 [ 1.48126829]]
[[-0.81485087]
 [ 1.48126709]]
[[-0.81485158]
 [ 1.48126638]]
[[-0.8148526 ]
 [ 1.48126519]]
[[-0.81485349]
 [ 1.48126411]]
[[-0.81485391]
 [ 1.48126352]]
[[-0.81485462]
 [ 1.48126268]]
[[-0.81485575]
 [ 1.48126173]]
[[-0.81485653]
 [ 1.48126125]]
[[-0.81485772]
 [ 1.48126054]]
[[-0.81485873]
 [ 1.48125947]]
[[-0.81485975]
 [ 1.48125863]]
[[-0.81486076]
 [ 1.4812578 ]]
[[-0.81486189]
 [ 1.48125708]]
[[-0.81486261]
 [ 1.48125625]]
[[-0.81486338]
 [ 1.48125529]]
[[-0.81486422]
 [ 1.4812547 ]]
[[-0.81486553]
 [ 1.4812535 ]]
[[-0.81486624]
 [ 1.48125279]]
[[-0.814

[[-0.81534028]
 [ 1.48081243]]
[[-0.81534147]
 [ 1.48081148]]
[[-0.81534225]
 [ 1.480811  ]]
[[-0.81534344]
 [ 1.48081028]]
[[-0.81534445]
 [ 1.48080921]]
[[-0.81534547]
 [ 1.48080838]]
[[-0.81534648]
 [ 1.48080754]]
[[-0.81534761]
 [ 1.48080683]]
[[-0.81534833]
 [ 1.48080599]]
[[-0.81534916]
 [ 1.48080492]]
[[-0.81535   ]
 [ 1.48080432]]
[[-0.81535131]
 [ 1.48080313]]
[[-0.81535202]
 [ 1.48080242]]
[[-0.81535304]
 [ 1.48080122]]
[[-0.81535393]
 [ 1.48080015]]
[[-0.81535435]
 [ 1.48079956]]
[[-0.81535506]
 [ 1.48079872]]
[[-0.81535625]
 [ 1.48079777]]
[[-0.81535703]
 [ 1.48079729]]
[[-0.81535822]
 [ 1.48079658]]
[[-0.81535923]
 [ 1.4807955 ]]
[[-0.81536025]
 [ 1.48079467]]
[[-0.81536126]
 [ 1.48079383]]
[[-0.81536239]
 [ 1.48079312]]
[[-0.81536311]
 [ 1.48079228]]
[[-0.81536394]
 [ 1.48079121]]
[[-0.81536478]
 [ 1.48079062]]
[[-0.81536609]
 [ 1.48078942]]
[[-0.8153668 ]
 [ 1.48078871]]
[[-0.81536782]
 [ 1.48078752]]
[[-0.81536871]
 [ 1.48078644]]
[[-0.81536913]
 [ 1.48078585]]
[[-0.815

### 3. 神经网络进一步优化

#### 指数衰减

In [15]:
global_step = tf.Variable(0)

learning_rate = tf.train.exponential_decay(0.1, global_step, 1, 0.96, staircase=True)

x = tf.Variable(tf.constant(5, dtype=tf.float32), name="x")
y = tf.square(x)
learning_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(y, global_step=global_step)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    if i % 10 == 9:
        learning_rate_value = sess.run(learning_rate)
        x_value = sess.run(x)
        print("After %s iteration(s): x%s is %f, learning rate is %f."% (i+1, i+1, x_value, learning_rate_value))

After 5000 iteration(s): x5000 is 5.000000, learning rate is 0.100000.


#### 过拟合

In [17]:
weights = tf.constant([[1.0, -2.0], [-3.0, 4.0]])
with tf.Session() as sess:
    print(sess.run(tf.contrib.layers.l1_regularizer(.5)(weights)))
    print(sess.run(tf.contrib.layers.l2_regularizer(.5)(weights)))

5.0
7.5


In [35]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

dataset_size = 200
data = []
label = []
np.random.seed(0)

# 以原点为圆心，半径为1的圆把散点划分成红蓝两部分，并加入随机噪音。
for i in range(dataset_size):
    x1 = np.random.uniform(-1,1)
    x2 = np.random.uniform(0,2)
    if x1**2 + x2**2 <= 1:
        data.append([np.random.normal(x1, 0.1),np.random.normal(x2,0.1)])
        label.append(0)
    else:
        data.append([np.random.normal(x1, 0.1), np.random.normal(x2, 0.1)])
        label.append(1)
        
data = np.hstack(data).reshape(-1,2)
label = np.hstack(label).reshape(-1, 1)


def get_weight(shape, lam):
    var = tf.Variable(tf.random_normal(shape), dtype=tf.float32)
    tf.add_to_collection('losses', tf.contrib.layers.l2_regularizer(lam)(var))
    
    return var

x = tf.placeholder(tf.float32, shape=(None, 2))
y_ = tf.placeholder(tf.float32, shape=(None, 1))

batch_size = 8
layer_dimension = [2, 10, 10, 10, 1]
n_layers = len(layer_dimension)

cur_layer = x
in_dimension = layer_dimension[0]

for i in range(1, n_layers):
    out_dimension = layer_dimension[i]
    weight = get_weight([in_dimension, out_dimension], 0.001)
    bias = tf.constant(0.1, shape=[out_dimension])
    
    cur_layer = tf.nn.relu(tf.matmul(cur_layer, weight) + bias)
    in_dimension = layer_dimension[i]
    
mse_loss = tf.reduce_mean(tf.square(y_ - cur_layer))

tf.add_to_collection('losses', mse_loss)

loss = tf.add_n(tf.get_collection('losses'))

train_op = tf.train.AdadeltaOptimizer(0.001).minimize(mse_loss)
training_step = 10000

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    for i in range(train_step):
        sess.run(train_op, feed_dict={x: data, y_:label})
        if i % 1000 == 999:
            print("After %d steps, loss: %f" % (i, sess.run(loss, feed_dict={x: data, y_: label})))

TypeError: Failed to convert object of type <class 'function'> to Tensor. Contents: <function l2_regularizer.<locals>.l2 at 0x000001CB4492BAE8>. Consider casting elements to a supported type.

#### 滑动平均模型

In [37]:
v1 = tf.Variable(0, dtype=tf.float32)
step = tf.Variable(0, trainable=False)

ema = tf.train.ExponentialMovingAverage(0.99, step)
maintain_averages_op = ema.apply([v1])

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    print(sess.run([v1, ema.average(v1)]))
    
    sess.run(tf.assign(v1, 5))
    sess.run(maintain_averages_op)
    print(sess.run([v1, ema.average(v1)]))
    
    sess.run(tf.assign(step, 10000))
    sess.run(tf.assign(v1, 10))
    sess.run(maintain_averages_op)
    print(sess.run([v1, ema.average(v1)]))
    
    sess.run(maintain_averages_op)
    print(sess.run([v1, ema.average(v1)]))

[0.0, 0.0]
[5.0, 4.5]
[10.0, 4.5549998]
[10.0, 4.6094499]
